#! /bin/sh
#
# submit.sh
# Copyright (C) 2019 Libao Jin <jinlibao@outlook.com>
#
# Distributed under terms of the MIT license.
#

MORAN_PARTITION=moran
MORAN_MAX_NODES=128
MORAN_NODES=16
MORAN_NTASKS_PER_NODE=16
MORAN_MEM=128000

MORAN_HUGEMEM_PARTITION=moran-bigmem-gpu
MORAN_HUGEMEM_MAX_NODES=2
MORAN_HUGEMEM_NODES=2
MORAN_HUGEMEM_NTASKS_PER_NODE=16
MORAN_HUGEMEM_MEM=512000

MORAN_HUGEMEM_PARTITION=moran-hugemem
MORAN_HUGEMEM_MAX_NODES=2
MORAN_HUGEMEM_NODES=2
MORAN_HUGEMEM_NTASKS_PER_NODE=8
MORAN_HUGEMEM_MEM=1024000

TETON_PARTITION=teton
TETON_MAX_NODES=128
TETON_NODES=8
TETON_NTASKS_PER_NODE=32
TETON_MEM=128000

TETON_KNL_PARTITION=teton-knl
TETON_KNL_MAX_NODES=12
TETON_KNL_NODES=8
TETON_KNL_NTASKS_PER_NODE=288
TETON_KNL_MEM=384000

TETON_HUGEMEM_PARTITION=teton-hugemem
TETON_HUGEMEM_MAX_NODES=10
TETON_HUGEMEM_NODES=8
TETON_HUGEMEM_NTASKS_PER_NODE=32
TETON_HUGEMEM_MEM=1024000

TETON_GPU_PARTITION=teton-gpu
TETON_GPU_MAX_NODES=8
TETON_GPU_NODES=8
TETON_GPU_NTASKS_PER_NODE=32
TETON_GPU_MEM=512000

PARTITION=$TETON_KNL_PARTITION
NODES=$TETON_KNL_NODES
NTASKS_PER_NODE=$TETON_KNL_NTASKS_PER_NODE
MEM=$TETON_KNL_MEM
export NCPU=`echo $NODES \* $NTASKS_PER_NODE|bc`
#sbatch --partition=$PARTITION --nodes=$NODES --ntasks-per-node=$NTASKS_PER_NODE --mem=$MEM task.sh

PARTITION=$TETON_HUGEMEM_PARTITION
NODES=$TETON_HUGEMEM_NODES
NTASKS_PER_NODE=$TETON_HUGEMEM_NTASKS_PER_NODE
MEM=$TETON_HUGEMEM_MEM
export NCPU=`echo $NODES \* $NTASKS_PER_NODE|bc`
#sbatch --partition=$PARTITION --nodes=$NODES --ntasks-per-node=$NTASKS_PER_NODE --mem=$MEM task.sh

PARTITION=$TETON_GPU_PARTITION
NODES=$TETON_GPU_NODES
NTASKS_PER_NODE=$TETON_GPU_NTASKS_PER_NODE
MEM=$TETON_GPU_MEM
export NCPU=`echo $NODES \* $NTASKS_PER_NODE|bc`
#sbatch --partition=$PARTITION --nodes=$NODES --ntasks-per-node=$NTASKS_PER_NODE --mem=$MEM task.sh

PARTITION=$TETON_PARTITION
NODES=$TETON_NODES
NTASKS_PER_NODE=$TETON_NTASKS_PER_NODE
MEM=$TETON_MEM
export NCPU=`echo $NODES \* $NTASKS_PER_NODE|bc`
sbatch --partition=$PARTITION --nodes=$NODES --ntasks-per-node=$NTASKS_PER_NODE --mem=$MEM task.sh
