#! /bin/bash
#
# submit_task.sh
# Copyright (C) 2019 Libao Jin <jinlibao@outlook.com>
#
# Distributed under terms of the MIT license.
#

MORAN_PARTITION=moran
MORAN_MAX_NODES=128
MORAN_NODES=16
MORAN_NTASKS_PER_NODE=16
MORAN_MEM=128000

MORAN_GPU_PARTITION=moran-bigmem-gpu
MORAN_GPU_MAX_NODES=2
MORAN_GPU_NODES=2
MORAN_GPU_NTASKS_PER_NODE=16
MORAN_GPU_MEM=512000

MORAN_HUGEMEM_PARTITION=moran-hugemem
MORAN_HUGEMEM_MAX_NODES=2
MORAN_HUGEMEM_NODES=2
MORAN_HUGEMEM_NTASKS_PER_NODE=8
MORAN_HUGEMEM_MEM=1024000

TETON_PARTITION=teton
TETON_MAX_NODES=128
TETON_NODES=8
TETON_NTASKS_PER_NODE=32
TETON_MEM=128000

TETON_GPU_PARTITION=teton-gpu
TETON_GPU_MAX_NODES=8
TETON_GPU_NODES=8
TETON_GPU_NTASKS_PER_NODE=32
TETON_GPU_MEM=512000

TETON_HUGEMEM_PARTITION=teton-hugemem
TETON_HUGEMEM_MAX_NODES=10
TETON_HUGEMEM_NODES=10
TETON_HUGEMEM_NTASKS_PER_NODE=32
TETON_HUGEMEM_MEM=1024000

TETON_KNL_PARTITION=teton-knl
TETON_KNL_MAX_NODES=12
TETON_KNL_NODES=11
TETON_KNL_NTASKS_PER_NODE=288
TETON_KNL_MEM=384000

PARTITION[0]=$MORAN_PARTITION
NODES[0]=$MORAN_NODES
NTASKS_PER_NODE[0]=$MORAN_NTASKS_PER_NODE
MEM[0]=$MORAN_MEM

PARTITION[1]=$MORAN_GPU_PARTITION
NODES[1]=$MORAN_GPU_NODES
NTASKS_PER_NODE[1]=$MORAN_GPU_NTASKS_PER_NODE
MEM[1]=$MORAN_GPU_MEM

PARTITION[2]=$MORAN_HUGEMEM_PARTITION
NODES[2]=$MORAN_HUGEMEM_NODES
NTASKS_PER_NODE[2]=$MORAN_HUGEMEM_NTASKS_PER_NODE
MEM[2]=$MORAN_HUGEMEM_MEM

PARTITION[3]=$TETON_PARTITION
NODES[3]=$TETON_NODES
NTASKS_PER_NODE[3]=$TETON_NTASKS_PER_NODE
MEM[3]=$TETON_MEM

PARTITION[4]=$TETON_GPU_PARTITION
NODES[4]=$TETON_GPU_NODES
NTASKS_PER_NODE[4]=$TETON_GPU_NTASKS_PER_NODE
MEM[4]=$TETON_GPU_MEM

PARTITION[5]=$TETON_HUGEMEM_PARTITION
NODES[5]=$TETON_HUGEMEM_NODES
NTASKS_PER_NODE[5]=$TETON_HUGEMEM_NTASKS_PER_NODE
MEM[5]=$TETON_HUGEMEM_MEM

PARTITION[6]=$TETON_KNL_PARTITION
NODES[6]=$TETON_KNL_NODES
NTASKS_PER_NODE[6]=$TETON_KNL_NTASKS_PER_NODE
MEM[6]=$TETON_KNL_MEM

if [[ $OSTYPE == darwin* ]]     # MacBook Pro @ libaooutrage (macOS)
then
    PROJECT_DIR=/Users/libao/Documents/work/projects/research/Tweet-Spatial-Analysis
    DATA_DIR=/Users/libao/Documents/data/twitter/csv
elif [[ $OSTYPE == linux-gnu ]] # Teton @ UWyo ARCC (Linux)
then
    PROJECT_DIR=/home/ljin1/repos/Tweet-Spatial-Analysis
    DATA_DIR=/gscratch/ljin1/data/twitter/csv/output/10-24-10000
fi

# Set up output directory
if [ ! -d $DATA_DIR ]; then
    mkdir -p $DATA_DIR
fi

k=0
ROW[0]=0
ROW[1]=4000
ROW[2]=10000
ROW[3]=16000
ROW[4]=57909

ELLIPSECSV[0]=$DATA_DIR/tweets_mean_all_10000_0.85.csv
ELLIPSECSV[1]=$DATA_DIR/tweets_mean_all_10000_0.95.csv
ELLIPSECSV[2]=$DATA_DIR/tweets_mean_all_10000_0.99.csv
ELLIPSECSV[3]=$DATA_DIR/tweets_mean_all_10000_1.00.csv
ELLIPSECSV[4]=$DATA_DIR/tweets_median_non_working_10000_0.85.csv
ELLIPSECSV[5]=$DATA_DIR/tweets_median_non_working_10000_0.95.csv
ELLIPSECSV[6]=$DATA_DIR/tweets_median_non_working_10000_0.99.csv
ELLIPSECSV[7]=$DATA_DIR/tweets_median_non_working_10000_1.00.csv
ELLIPSECSV[8]=$DATA_DIR/tweets_median_working_10000_0.85.csv
ELLIPSECSV[9]=$DATA_DIR/tweets_median_working_10000_0.95.csv
ELLIPSECSV[10]=$DATA_DIR/tweets_median_working_10000_0.99.csv
ELLIPSECSV[11]=$DATA_DIR/tweets_median_working_10000_1.00.csv
export MAT_A_FILE=$DATA_DIR/matmul/mat_A.csv
export MAT_B_FILE=$DATA_DIR/matmul/mat_B.csv
export MAT_C_FILE=$DATA_DIR/matmul/mat_C.csv

for (( j=0; j<1; ++j ))
do
    export ROWS=${ROW[j]}
    for (( i=0; i<12; ++i ))
    do
        export ELLIPSECSV_FILE=${ELLIPSECSV[i]}
        export FROM=2147825826
        export TO=414498534
        export NCPU=`echo ${NODES[k]} \* ${NTASKS_PER_NODE[k]}|bc`
        sbatch --partition=${PARTITION[k]} --nodes=${NODES[k]} --ntasks-per-node=${NTASKS_PER_NODE[k]} --mem=${MEM[k]} task.sh
    done
done
